"""Alter table container (add column status)

Revision ID: 1783ad4e8ab4
Revises: 02d72588b9bd
Create Date: 2022-12-12 20:05:42.495067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1783ad4e8ab4'
down_revision = '02d72588b9bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('container', sa.Column('status', sa.Enum('empty', 'filling', 'full', name='statuscontainer'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('container', 'status')
    # ### end Alembic commands ###
