"""Create route points model

Revision ID: 6bab5c53db3b
Revises: 1783ad4e8ab4
Create Date: 2022-12-14 22:52:38.556488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bab5c53db3b'
down_revision = '1783ad4e8ab4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('cumulative_vol', sa.Float(), nullable=False),
    sa.Column('points', sa.PickleType(), nullable=True),
    sa.Column('status', sa.Enum('opened', 'closed', name='statusroute'), nullable=False),
    sa.PrimaryKeyConstraint('route_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    # ### end Alembic commands ###
